export default {
    HOMEPAGE: '/',
    JOB_SEARCH: '/viec-lam',
    JOB_SEARCH_DETAIL: '/viec-lam/chi-tiet',
    MATCHING_JOBS: '/viec-lam-phu-hop',
    SUBPAGE: '/subpage',
    LOGIN: '/login',
    REGISTER: '/register',

    MANAGER_REGISTER: '/tuyen-dung/app/register',
    MANAGER_LOGIN: '/tuyen-dung/app/login',
    DASHBOARD_HOME: '/tuyen-dung/app/dashboard',
    DASHBOARD_POST: '/tuyen-dung/app/emloyer-verify?context=create-job',
    DASHBOARD_SEARCH: '/tuyen-dung/app/emloyer-verify?context=search-cv',
    DASHBOARD_CAMPAIGN: '/tuyen-dung/app/campaign',
    DASHBOARD_CAMPAIGN_PUSHING: '/tuyen-dung/app/campaign?filter=pushing',
    DASHBOARD_CAMPAIGN_CV: '/tuyen-dung/app/campaign?filter=cv',
    DASHBOARD_CV_MANAGEMENT: '/tuyen-dung/app/cv-management',
    DASHBOARD_CART: '/tuyen-dung/app/cart',
    DASHBOARD_CONNECT: '/tuyen-dung/app/connect',
    DASHBOARD_ACCOUNT_SETTING: '/tuyen-dung/app/account-setting',
    DASHBOARD_INVOICE: '/tuyen-dung/app/invoice',
    DASHBOARD_EKYC: '/tuyen-dung/app/ekyc/notification',
    DASHBOARD_POST_CAMPAIGN: '/tuyen-dung/app/jobs/create-campaign',
    DASHBOARD_POST_JOB: '/tuyen-dung/app/jobs/create-job',
};
