export default {
    HOMEPAGE: '/',
    JOB_SEARCH: '/viec-lam',
    JOB_SEARCH_DETAIL: '/viec-lam/chi-tiet/:id/:slug',
    MATCHING_JOBS: '/viec-lam-phu-hop',
    MANAGER_REGISTER: '/tuyen-dung/app/register',
    MANAGER_LOGIN: '/tuyen-dung/app/login',
    DASHBOARD_ADMIN: '/tuyen-dung/app/dashboard',
    DASHBOARD_POST: '/tuyen-dung/app/emloyer-verify',
    DASHBOARD_SEARCH: '/tuyen-dung/app/emloyer-verify',
    DASHBOARD_CART: '/tuyen-dung/app/cart',
    DASHBOARD_CONNECT: '/tuyen-dung/app/connect',
    SUBPAGE: '/subpage',
    LOGIN: '/login',
    REGISTER: '/register',
};
