import SkeletonJobSectionComponent from './SkeletonJobSectionComponent/SkeletonJobSectionComponent';
import SkeletonCompanyComponent from './SkeletonCompanyComponent/SkeletonCompanyComponent';
import SkeletonJobDetailPage from './SkeletonJobDetailPage/SkeletonJobDetailPage';
import SkeletonRecruimentCampaignComponent from './SkeletonRecruimentCampaignComponent/SkeletonRecruimentCampaignComponent';
import SkeletonCompanySquareComponent from './SkeletonCompanySquareComponent/SkeletonCompanySquareComponent';
export { SkeletonJobSectionComponent, SkeletonCompanyComponent, SkeletonJobDetailPage, SkeletonRecruimentCampaignComponent, SkeletonCompanySquareComponent };
