import { useState } from 'react';
import { useDispatch } from 'react-redux';
import classNames from 'classnames/bind';
import PropTypes from 'prop-types';

import { FaLock } from 'react-icons/fa';
import { FaCircleInfo } from 'react-icons/fa6';
import { HiArrowTrendingUp, HiArrowTrendingDown } from 'react-icons/hi2';

import styles from './JobDetailBody.module.scss';
import { images } from '../../../../../assets';
import JobSuggest from './JobSuggest/JobSuggest';
import HeaderDynamic from '../HeaderDynamic/HeaderDynamic';
import JobSummary from './JobSummary/JobSummary';
import JobCategory from '../JobCategory/JobCategory';
import JobSuitable from '../JobSuitable/JobSuitable';
import CompanySummary from '../CompanySummary/CompanySummary';
import JobReport from '../JobReport/JobReport';
import SuggestCourseSlide from './SuggestCourseSlide/SuggestCourseSlide';
import { showModal } from '../../../../../redux/features/modal/modalSlice';
import { Modal } from '../../../../../components/common';
import { ModalApplyComponent } from '../../../../../components';

const cx = classNames.bind(styles);

const JobDetailBody = ({ job, state }) => {
    const dispatch = useDispatch();
    const [stateTab, setStateTab] = useState('detail');

    const listDescription = [
        {
            id: 1,
            title: 'Mô tả công việc',
            content: job.job_description,
        },
        {
            id: 2,
            title: 'Yêu cầu ứng viên',
            content: job.job_requirement,
        },
        {
            id: 3,
            title: 'Quyền lợi',
            content: job.job_benefit,
        },
        {
            id: 4,
            title: 'Địa điểm làm việc',
            content: job.address,
        },
        {
            id: 5,
            title: 'Thời gian làm việc',
            is_apply: 'false',
            content: job.working_times,
        },
    ];

    const stateTrend = {
        percent: 8,
        status: 'down',
    };

    const suggest_jobs = [
        {
            company: {
                name: 'CÔNG TY TNHH LITEFINANCE ACADEMY',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/nx7aRh5rLXMa6wNN7rnSogsiCijAK7fL_1700898275____cc71b63b7d1522ebc3843d911f0b7a73.jpeg',
                url: 'https://www.topcv.vn/cong-ty/fe-credit/81412.html',
            },
            id: 1263451,
            title: 'Nh\u00e2n Vi\u00ean Thu Ph\u00ed T\u00edn D\u1ee5ng Th\u1ecb Tr\u01b0\u1eddng',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>B\u00ecnh D\u01b0\u01a1ng<br/>B\u00ecnh Thu\u1eadn<br/>B\u00e0 R\u1ecba-V\u0169ng T\u00e0u<br/>\u0110\u1ed3ng Nai<br/>Long An<br/>B\u1eafc Ninh<br/>L\u00e0o Cai<br/>Qu\u1ea3ng Ninh<br/>H\u1ea3i Ph\u00f2ng<br/>An Giang</p>",
            short_cities: 'Long An & 9 n\u01a1i kh\u00e1c',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '2 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-thu-phi-tin-dung-thi-truong/1263451.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'true',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'true',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N \u0110\u1ea6U T\u01af HBR HOLDINGS',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/eghXad8xcqCaobJDLUZqUATF0i14mp67_1708681146____7e252952d1e2fab99813dfaa0d39f50c.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-dau-tu-hbr-holdings/141191.html',
            },
            id: 1263440,
            title: 'Chuy\u00ean Vi\u00ean Kinh Doanh (Thu Nh\u1eadp 15-30tr/Th\u00e1ng, Th\u1eed Vi\u1ec7c 100% L\u01b0\u01a1ng)',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n, C\u1ea7u Gi\u1ea5y, H\u00e0 \u0110\u00f4ng, Th\u1ea1ch Th\u1ea5t</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-kinh-doanh-thu-nhap-15-30tr-thang-thu-viec-100-luong/1263440.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:30 \u0111\u1ebfn 17:30)',
                'Th\u1ee9 7 (t\u1eeb 08:00 \u0111\u1ebfn 12:00)',
                'T\u1eeb Th\u1ee9 2 \u0111\u1ebfn S\u00e1ng Th\u1ee9 7 (ngh\u1ec9 1,5 ng\u00e0y/tu\u1ea7n). \u0110\u01b0\u1ee3c l\u1ef1a ch\u1ecdn ca l\u00e0m vi\u1ec7c:\r\n- Ca 1: 08h30 - 17h30, ngh\u1ec9 tr\u01b0a 12h00 - 13h30\r\n- Ca 2: 13h30 - 21h30',
            ],
        },
        {
            company: {
                name: 'FE CREDIT',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/4309b044c7147d553222bc769da5161d-6194b4d027185.jpg',
                url: 'https://www.topcv.vn/cong-ty/fe-credit/81412.html',
            },
            id: 1263435,
            title: 'Nh\u00e2n Vi\u00ean X\u1eed L\u00fd T\u00edn D\u1ee5ng Th\u1ecb Tr\u01b0\u1eddng',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh<br/>Long An<br/>B\u00e0 R\u1ecba-V\u0169ng T\u00e0u<br/>B\u1eafc Ninh<br/>Th\u1eeba Thi\u00ean Hu\u1ebf<br/>V\u0129nh Ph\u00fac<br/>H\u00e0 Nam<br/>H\u1ea3i D\u01b0\u01a1ng<br/>Y\u00ean B\u00e1i<br/>B\u1eafc Giang</p>",
            short_cities: 'Long An & 9 n\u01a1i kh\u00e1c',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '3 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-xu-ly-tin-dung-thi-truong/1263435.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'FE CREDIT',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/4309b044c7147d553222bc769da5161d-6194b4d027185.jpg',
                url: 'https://www.topcv.vn/cong-ty/fe-credit/81412.html',
            },
            id: 1263420,
            title: 'Nh\u00e2n Vi\u00ean X\u1eed L\u00fd T\u00edn Ch\u1ea5p T\u1ea1i Th\u1ecb Tr\u01b0\u1eddng',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i<br/>B\u1eafc Giang<br/>Th\u00e1i Nguy\u00ean<br/>B\u1eafc Ninh<br/>H\u01b0ng Y\u00ean<br/>B\u00ecnh Thu\u1eadn<br/>B\u1ebfn Tre<br/>An Giang<br/>C\u00e0 Mau<br/>T\u00e2y Ninh</p>",
            short_cities: 'C\u00e0 Mau & 9 n\u01a1i kh\u00e1c',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-xu-ly-tin-chap-tai-thi-truong/1263420.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng ty C\u1ed5 ph\u1ea7n D\u01b0\u1ee1ng sinh Y d\u01b0\u1ee3c Sao Ph\u01b0\u01a1ng \u0110\u00f4ng',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/rPCNoFEBqjn0xSRmBnP1qSz4d0pgu7Qd_1646886967____d05cd2fcf1c70310dae9bd323e481747.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-duong-sinh-y-duoc-sao-phuong-dong/92048.html',
            },
            id: 1263344,
            title: 'Tr\u01b0\u1edfng Nh\u00f3m Kinh Doanh, L\u01b0\u01a1ng C\u1ee9ng 15 - 20 Tri\u1ec7u T\u1ea1i H\u00e0 N\u1ed9i',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Hai B\u00e0 Tr\u01b0ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '8 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/truong-nhom-kinh-doanh-luong-cung-15-20-trieu-tai-ha-noi/1263344.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 17:00)',
                'T\u1eeb th\u1ee9 2 \u0111\u1ebfn th\u1ee9 6. th\u1ee9 7 ngh\u1ec9 c\u00e1ch tu\u1ea7n',
            ],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N T\u1eacP \u0110O\u00c0N APEC GROUP',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-tap-doan-apec-group-64006b5b4ab8f.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tap-doan-apec-group/135699.html',
            },
            id: 1263206,
            title: 'Nh\u00e2n Vi\u00ean T\u01b0 V\u1ea5n Tuy\u1ec3n Sinh Du H\u1ecdc Ngh\u1ec1 - T\u1ea1i H\u00e0 N\u1ed9i - Thu Nh\u1eadp 20 - 50 Tri\u1ec7u',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: C\u1ea7u Gi\u1ea5y</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '20 - 50 tri\u1ec7u',
            updated_at_str: '5 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-tu-van-tuyen-sinh-du-hoc-nghe-tai-ha-noi-thu-nhap-20-50-trieu/1263206.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 17:50)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH AIRPIPE VI\u1ec6T NAM',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/rOTqXZC37rhTvijBJAOdVNnMxOxGQXcl_1708488522____63ad01438672ef4893f4b87cb9e7d791.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-airpipe-viet-nam/163323.html',
            },
            id: 1262999,
            title: 'K\u1ebf To\u00e1n T\u1ed5ng H\u1ee3p (Ti\u1ebfng Trung/Ti\u1ebfng Anh) - Th\u1ee7 \u0110\u1ee9c',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Th\u1ee7 \u0110\u1ee9c</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '17 - 20 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/ke-toan-tong-hop-tieng-trung-tieng-anh-thu-duc/1262999.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/05/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 59,
            remain_deadline_by_hour: 1437,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 2 - Th\u1ee9 7 (t\u1eeb 08:00 \u0111\u1ebfn 17:00)',
                '\u0110\u01b0\u1ee3c ngh\u1ec9 hai bu\u1ed5i chi\u1ec1u th\u1ee9 7 trong th\u00e1ng.',
            ],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N HANOTECH VI\u1ec6T NAM',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-hanotech-viet-nam-60e3e2f2b7a58.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-hanotech-viet-nam/18962.html',
            },
            id: 1262968,
            title: 'Nh\u00e2n Vi\u00ean K\u1ebf To\u00e1n T\u1ed5ng H\u1ee3p -Thu\u1ebf (Thu Nh\u1eadp 15-20 Tri\u1ec7u) T\u1ea1i H\u00e0 N\u1ed9i',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: H\u00e0 \u0110\u00f4ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-ke-toan-tong-hop-thue-thu-nhap-15-20-trieu-tai-ha-noi/1262968.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '23/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 40,
            remain_deadline_by_hour: 981,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N C\u00d4NG NGH\u1ec6 AIT',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/UtBcv3qwFXoRfddEiXKuncKahYsTxLr8_1683860942____1415486e4681e77d3ef13ad75698b8c2.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-cong-nghe-ait/142920.html',
            },
            id: 1262907,
            title: 'Middle Backend Dev (Java, Spring, SQL)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: C\u1ea7u Gi\u1ea5y</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '25 - 35 tri\u1ec7u',
            updated_at_str: '8 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/middle-backend-dev-java-spring-sql/1262907.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'Th\u1ea9m M\u1ef9 Vi\u1ec7n Boston Clinic',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/tham-my-vien-boston-clinic-b3b6c51796f207b870af32188d87a4f5-65f121cf45fe7.jpg',
                url: 'https://www.topcv.vn/cong-ty/tham-my-vien-boston-clinic/165578.html',
            },
            id: 1262739,
            title: 'Nh\u00e2n Vi\u00ean Telesale - Kh\u00f4ng Y\u00eau C\u1ea7u Kinh Nghi\u1ec7m (Thu Nh\u1eadp 15-30 Tri\u1ec7u/Th\u00e1ng, Ph\u1ee5 C\u1ea5p \u0102n Tr\u01b0a + Ph\u1ee5 C\u1ea5p Laptop)',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Ba \u0110\u00ecnh</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '12 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-telesale-khong-yeu-cau-kinh-nghiem-thu-nhap-15-30-trieu-thang-phu-cap-an-trua-phu-cap-laptop/1262739.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'true',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 2 - Ch\u1ee7 nh\u1eadt (t\u1eeb 08:00 \u0111\u1ebfn 17:30)',
                '\u0110\u0103ng k\u00ed ngh\u1ec9 1 ng\u00e0y b\u1ea5t k\u00ec trong tu\u1ea7n',
            ],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N C\u00d4NG NGH\u1ec6 GI\u00c1O D\u1ee4C NATIVE X',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/QMOE8IDE8fymcxwi2oQSqfd0xwhPTLUv_1685700767____bf16a9bce0dec8cc42da7a53953bf7c1.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-cong-nghe-giao-duc-native-x/144050.html',
            },
            id: 1262428,
            title: 'Nh\u00e2n Vi\u00ean T\u01b0 V\u1ea5n Kh\u00f3a H\u1ecdc (Telesales ) - T\u1ea1i H\u00e0 N\u1ed9i - Thu Nh\u1eadp 15 - 30 Tri\u1ec7u',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Ba \u0110\u00ecnh</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-tu-van-khoa-hoc-telesales-tai-ha-noi-thu-nhap-15-30-trieu/1262428.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '06/05/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 53,
            remain_deadline_by_hour: 1293,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH CMC CYBER SECURITY',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/wADV14D3mxDdN3Si5iNC32PvihdWExHV_1637206489____52b9e56079c77355b6dfbfe73f311843.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-cmc-cyber-security/81520.html',
            },
            id: 1262411,
            title: 'Product Owner - L\u01b0\u01a1ng T\u1eeb 25 - 50 Tri\u1ec7u',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: C\u1ea7u Gi\u1ea5y</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '25 - 50 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/product-owner-luong-tu-25-50-trieu/1262411.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 17:30)'],
        },
        {
            company: {
                name: 'C\u00f4ng ty CPTM Chaang Vi\u1ec7t Nam',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/YRvEOSnqKUshYSTBxGeeomRkwXZ5HcN0_1708309576____b73f1cbee8fe4ca555030b500e58fe04.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-cptm-chaang-viet-nam/23323.html',
            },
            id: 1262399,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh \u2013 Ph\u00e1t Tri\u1ec3n Th\u1ecb Tr\u01b0\u1eddng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Ho\u00e0ng Mai</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '2 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-phat-trien-thi-truong/1262399.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH S\u1ea2N XU\u1ea4T TH\u1ef0C PH\u1ea8M TO\u00c0N C\u1ea6U',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-san-xuat-thuc-pham-toan-cau/127783.html',
            },
            id: 1262122,
            title: 'Tr\u01b0\u1edfng Ph\u00f2ng H\u00e0nh Ch\u00ednh Nh\u00e2n S\u1ef1 - Thu Nh\u1eadp T\u1eeb 15 - 25 Tri\u1ec7u T\u1ea1i H\u1ea3i Ph\u00f2ng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ea3i Ph\u00f2ng: D\u01b0\u01a1ng Kinh</p>",
            short_cities: 'H\u1ea3i Ph\u00f2ng',
            salary: '15 - 25 tri\u1ec7u',
            updated_at_str: '7 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/truong-phong-hanh-chinh-nhan-su-thu-nhap-tu-15-25-trieu-tai-hai-phong/1262122.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['- Th\u1eddi gian: T\u1eeb 08h00-17h00, 1 th\u00e1ng ngh\u1ec9 4 ng\u00e0y'],
        },
        {
            company: {
                name: 'C\u00f4ng Ty C\u1ed5 Ph\u1ea7n D\u1ecbch V\u1ee5 V\u00e0 Th\u01b0\u01a1ng M\u1ea1i H\u01b0ng Long',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/wRC2rDVHgT6f8kpMq9P7vpb2ciDjEGIg_1648463381____c4455feafea3bdb902d12750b418e331.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-dich-vu-va-thuong-mai-hung-long/95025.html',
            },
            id: 1262029,
            title: 'Tr\u01b0\u1edfng Ph\u00f2ng Thi\u1ebft K\u1ebf B\u1ea3n V\u1ebd C\u00f4ng Tr\u00ecnh',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: 'Tr\u00ean 20 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/truong-phong-thiet-ke-ban-ve-cong-trinh/1262029.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 7 (t\u1eeb 08:00 \u0111\u1ebfn 17:30)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH TH\u01af\u01a0NG M\u1ea0I-D\u1ecaCH V\u1ee4 \u0110I\u1ec6N M\u1ea0NH PH\u01af\u01a0NG',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-tnhh-thuong-mai-dich-vu-dien-manh-phuong-62a1756e85cad.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-thuong-mai-dich-vu-dien-manh-phuong/105610.html',
            },
            id: 1150446,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh/ Sale Th\u1ecb Tr\u01b0\u1eddng/ \u0110\u1ea1i Di\u1ec7n B\u00e1n H\u00e0ng L\u0129nh V\u1ef1c \u0110i\u1ec7n (Y\u00eau C\u1ea7u Nam)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i<br/>Ngh\u1ec7 An<br/>H\u1ea3i D\u01b0\u01a1ng<br/>Mi\u1ec1n B\u1eafc</p>",
            short_cities: 'H\u00e0 N\u1ed9i & 3 n\u01a1i kh\u00e1c',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-sale-thi-truong-dai-dien-ban-hang-linh-vuc-dien-yeu-cau-nam/1150446.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'NEST BY AIA',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/nest-by-aia-e6628689f56af3945018f15b037dbe06-659d14c277ff9.jpg',
                url: 'https://www.topcv.vn/cong-ty/nest-by-aia/124208.html',
            },
            id: 882911,
            title: 'Chuy\u00ean Vi\u00ean Quan H\u1ec7 Kh\u00e1ch H\u00e0ng Kh\u00f4ng Y\u00eau C\u1ea7u Kinh',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 1, Qu\u1eadn 4, Qu\u1eadn 3, Qu\u1eadn 5, Qu\u1eadn 6, Qu\u1eadn 10, B\u00ecnh Th\u1ea1nh, T\u00e2n B\u00ecnh, Qu\u1eadn 2</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '16 - 37 tri\u1ec7u',
            updated_at_str: '15 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-quan-he-khach-hang-khong-yeu-cau-kinh/882911.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '27/03/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 13,
            remain_deadline_by_hour: 333,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng Ty TNHH A S\u00f3c',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-tnhh-a-soc-5f18ff857b322.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-a-soc/41266.html',
            },
            id: 1261955,
            title: 'Tr\u01b0\u1edfng Ph\u00f2ng H\u00e0nh Ch\u00ednh Nh\u00e2n S\u1ef1',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: H\u00e0 \u0110\u00f4ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '5 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/truong-phong-hanh-chinh-nhan-su/1261955.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 17:00)',
                'Ngh\u1ec9 2 chi\u1ec1u th\u1ee9 7/th\u00e1ng v\u00e0 t\u1ea5t c\u1ea3 ng\u00e0y ch\u1ee7 nh\u1eadt',
            ],
        },
        {
            company: {
                name: 'CTY TNHH R TECHNO VI\u1ec6T NAM',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cty-tnhh-r-techno-viet-nam-d50e5e9e47821a66eb1e8733264810b1-65f0fcaf57bea.jpg',
                url: 'https://www.topcv.vn/cong-ty/cty-tnhh-r-techno-viet-nam/165377.html',
            },
            id: 1261787,
            title: 'K\u1ef9 S\u01b0 Ph\u00e1t Tri\u1ec3n Ph\u1ea7n M\u1ec1m Nh\u00fang Matlab/Simulink T\u1ea1i HCM/ Nh\u1eadt B\u1ea3n - L\u01b0\u01a1ng Upto 70M',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: B\u00ecnh Th\u1ea1nh<br/>N\u01b0\u1edbc Ngo\u00e0i</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh, N\u01b0\u1edbc Ngo\u00e0i',
            salary: '30 - 66.4 tri\u1ec7u',
            updated_at_str: '15 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/ky-su-phat-trien-phan-mem-nhung-matlab-simulink-tai-hcm-nhat-ban-luong-upto-70m/1261787.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 07:30 \u0111\u1ebfn 16:30)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH TH\u01af\u01a0NG M\u1ea0I TIANXINGYUN VI\u1ec6T NAM',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-thuong-mai-tianxingyun-viet-nam/163825.html',
            },
            id: 1261759,
            title: 'Nh\u00e2n Vi\u00ean V\u1eadn H\u00e0nh S\u00e0n Th\u01b0\u01a1ng M\u1ea1i \u0110i\u1ec7n T\u1eed',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 10</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '9 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-van-hanh-san-thuong-mai-dien-tu/1261759.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N GI\u1ea2I PH\u00c1P THANH TO\u00c1N VI\u1ec6T T\u00cdN',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-giai-phap-thanh-toan-viet-tin/164629.html',
            },
            id: 1261723,
            title: 'K\u1ebf To\u00e1n T\u1ed5ng H\u1ee3p ( Thu Nh\u1eadp T\u1eeb 15 Tri\u1ec7u \u0110\u1ebfn 20 Tri\u1ec7u )',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 3</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '11 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/ke-toan-tong-hop-thu-nhap-tu-15-trieu-den-20-trieu/1261723.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH LOGISTICS XNK',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/x2u6EEgZBFaUgy0tTnanqvf2XmJ4uTms_1710236637____09ec6aab66edb4a4a2a2de8af6d869c5.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-logistics-xnk/165392.html',
            },
            id: 1261706,
            title: 'Nh\u00e2n Vi\u00ean Qu\u1ea3n L\u00fd V\u1eadn T\u1ea3i (Tuy\u1ec3n Nam)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Long Bi\u00ean</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '16 - 19 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-quan-ly-van-tai-tuyen-nam/1261706.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N GI\u1ea2I PH\u00c1P THANH TO\u00c1N VI\u1ec6T T\u00cdN',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-giai-phap-thanh-toan-viet-tin/164629.html',
            },
            id: 1261705,
            title: 'K\u1ebf To\u00e1n Tr\u01b0\u1edfng ( Thu Nh\u1eadp T\u1eeb 25 Tri\u1ec7u \u0110\u1ebfn 35 Tri\u1ec7u )',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 3</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '25 - 35 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/ke-toan-truong-thu-nhap-tu-25-trieu-den-35-trieu/1261705.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH LOGISTICS XNK',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/x2u6EEgZBFaUgy0tTnanqvf2XmJ4uTms_1710236637____09ec6aab66edb4a4a2a2de8af6d869c5.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-logistics-xnk/165392.html',
            },
            id: 1261692,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh Logistics',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Long Bi\u00ean</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 17 tri\u1ec7u',
            updated_at_str: '3 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-logistics/1261692.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 7 (t\u1eeb 08:00 \u0111\u1ebfn 17:00)\r\nNgh\u1ec9 2 Th\u1ee9 7/th\u00e1ng'],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N GI\u1ea2I PH\u00c1P THANH TO\u00c1N VI\u1ec6T T\u00cdN',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-giai-phap-thanh-toan-viet-tin/164629.html',
            },
            id: 1261684,
            title: 'Tr\u01b0\u1edfng Ph\u00f2ng H\u00e0nh Ch\u00ednh Nh\u00e2n S\u1ef1 ( Thu Nh\u1eadp T\u1eeb 20 Tri\u1ec7u \u0110\u1ebfn 30 Tri\u1ec7u )',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 3</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '20 - 30 tri\u1ec7u',
            updated_at_str: '9 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/truong-phong-hanh-chinh-nhan-su-thu-nhap-tu-20-trieu-den-30-trieu/1261684.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH B\u1ea2O HI\u1ec2M NH\u00c2N TH\u1ecc SUN LIFE VI\u1ec6T NAM',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-tnhh-bao-hiem-nhan-tho-sun-life-viet-nam-5fd03684a7cdd.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-bao-hiem-nhan-tho-sun-life-viet-nam/50224.html',
            },
            id: 1261674,
            title: 'Chuy\u00ean Vi\u00ean T\u01b0 V\u1ea5n T\u00e0i Ch\u00ednh C\u1ea5p Cao - K\u00eanh Li\u00ean K\u1ebft Ng\u00e2n H\u00e0ng TPBank - H\u1ed3 Ch\u00ed Minh',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: 'Tr\u00ean 15 tri\u1ec7u',
            updated_at_str: '16 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-tu-van-tai-chinh-cap-cao-kenh-lien-ket-ngan-hang-tpbank-ho-chi-minh/1261674.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng ty TNHH Gi\u00e1o D\u1ee5c v\u00e0 \u0110\u00e0o T\u1ea1o StarLink',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/Fi51bpCjchuHeCo3g2qnPMPJMPt5l2xJ_1699348271____28ebfb23fd351402380e19c1420d5531.jpeg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-giao-duc-va-dao-tao-starlink/149002.html',
            },
            id: 1261668,
            title: 'Qu\u1ea3n L\u00fd/ Gi\u00e1m S\u00e1t Ch\u1ea5t L\u01b0\u1ee3ng Trung T\u00e2m Ti\u1ebfng Anh (Full Time) - Thu Nh\u1eadp Upto 25 Tri\u1ec7u',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Hai B\u00e0 Tr\u01b0ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 25 tri\u1ec7u',
            updated_at_str: '2 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/quan-ly-giam-sat-chat-luong-trung-tam-tieng-anh-full-time-thu-nhap-upto-25-trieu/1261668.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'true',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [
                'Th\u1ee9 Hai \u0111\u1ebfn th\u1ee9 S\u00e1u: 14h30 - 21h30.\r\nS\u00e1ng Th\u1ee9 B\u1ea3y: 8h30 - 12h.\r\nC\u00f3 th\u1ec3 linh ho\u1ea1t \u0111\u1ed5i ca n\u1ebfu c\u1ea7n',
            ],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N T\u1eacP \u0110O\u00c0N TH\u00c9P POSHACO',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/mYcxD4P1Ufbx8rwH3NlbRDjLu93XSKx4_1710144285____a3f05ed536dd27fc1910f34dc66cce41.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tap-doan-thep-poshaco/165306.html',
            },
            id: 1261631,
            title: 'Nam Nh\u00e2n Vi\u00ean Kinh Doanh (Thu Nh\u1eadp Trung B\u00ecnh T\u1eeb 20 - 25 Tri\u1ec7u/Th\u00e1ng)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Nam T\u1eeb Li\u00eam<br/>Th\u00e1i B\u00ecnh<br/>H\u1ea3i D\u01b0\u01a1ng<br/>Ph\u00fa Th\u1ecd<br/>Thanh Ho\u00e1<br/>Ngh\u1ec7 An</p>",
            short_cities: 'H\u00e0 N\u1ed9i & 5 n\u01a1i kh\u00e1c',
            salary: '20 - 25 tri\u1ec7u',
            updated_at_str: '3 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nam-nhan-vien-kinh-doanh-thu-nhap-trung-binh-tu-20-25-trieu-thang/1261631.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH D\u1ecaCH V\u1ee4 V\u00c0 \u0110\u1ea6U T\u01af TH\u01af\u01a0NG M\u1ea0I H\u00d9NG AN',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-dich-vu-va-dau-tu-thuong-mai-hung-an/165448.html',
            },
            id: 1261302,
            title: 'Nh\u00e2n Vi\u00ean T\u01b0 V\u1ea5n Thu Nh\u1eadp 15-30Tri\u1ec7u/ Th\u00e1ng- \u0110i L\u00e0m Ngay',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-tu-van-thu-nhap-15-30trieu-thang-di-lam-ngay/1261302.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 7 (t\u1eeb 08:30 \u0111\u1ebfn 17:30)', 'ngh\u1ec9 tr\u01b0a 1h30'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH QU\u1ed0C T\u1ebe GEORGE GLORY VI\u1ec6T NAM',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cUJKHX0wgZ8hzYucaAgb5VzDQ49lvgk7_1702534494____b41fa9abe4472da4863ae27820e1d463.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-quoc-te-george-glory-viet-nam/160251.html',
            },
            id: 1261148,
            title: 'Chuy\u00ean Vi\u00ean Song Ng\u1eef Anh Trung/ Chuy\u00ean Vi\u00ean D\u1ef1 \u00c1n/Chuy\u00ean Vi\u00ean Nghi\u1ec7p V\u1ee5 Ki\u00eam Tr\u1ee3 L\u00fd Gi\u00e1m \u0110\u1ed1c, Thu Nh\u1eadp L\u00ean \u0110\u1ebfn 35 Tri\u1ec7u T\u1ea1i H\u1ea3i D\u01b0\u01a1ng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ea3i D\u01b0\u01a1ng: Ninh Giang</p>",
            short_cities: 'H\u1ea3i D\u01b0\u01a1ng',
            salary: '25 - 35 tri\u1ec7u',
            updated_at_str: '5 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-song-ngu-anh-trung-chuyen-vien-du-an-chuyen-vien-nghiep-vu-kiem-tro-ly-giam-doc-thu-nhap-len-den-35-trieu-tai-hai-duong/1261148.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng ty C\u1ed5 ph\u1ea7n \u0110\u1ea7u t\u01b0 v\u00e0 Ph\u00e1t tri\u1ec3n du l\u1ecbch Ravi',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-dau-tu-va-phat-trien-du-lich-ravi-63ecad7250fe9.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-dau-tu-va-phat-trien-du-lich-ravi/91337.html',
            },
            id: 1260827,
            title: 'Nh\u00e2n Vi\u00ean \u0110\u1eb7t L\u1ecbch H\u1eb9n - Kh\u00f4ng Sale, Cung C\u1ea5p 100% Data - Thu Nh\u1eadp \u0110\u1ebfn 50tr/Th\u00e1ng',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '20 - 50 tri\u1ec7u',
            updated_at_str: '5 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-dat-lich-hen-khong-sale-cung-cap-100-data-thu-nhap-den-50tr-thang/1260827.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'true',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 7 (t\u1eeb 08:30 \u0111\u1ebfn 18:00)'],
        },
        {
            company: {
                name: 'C\u00f4ng Ty TNHH Th\u01b0\u01a1ng M\u1ea1i V\u00e0 \u0110\u1ea7u T\u01b0 SRT Mi\u1ec1n Trung',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-tnhh-thuong-mai-va-dau-tu-srt-mien-trung-16ce20a7043ae8d76b5a40987d5f5cc3-65f00ec2ada1d.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-thuong-mai-va-dau-tu-srt-mien-trung/165369.html',
            },
            id: 1260688,
            title: 'Chuy\u00ean Vi\u00ean Kinh Doanh B\u1ea5t \u0110\u1ed9ng S\u1ea3n - \u0110i L\u00e0m Ngay',
            company_short_description: '',
            cities: "<p style='text-align: left'>\u0110\u00e0 N\u1eb5ng</p>",
            short_cities: '\u0110\u00e0 N\u1eb5ng',
            salary: '25 - 100 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-kinh-doanh-bat-dong-san-di-lam-ngay/1260688.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY CP QU\u1ed0C T\u1ebe ICO',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-cp-quoc-te-ico-63be5420e0fc3.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-cp-quoc-te-ico/130639.html',
            },
            id: 1260648,
            title: 'Ph\u00f3 T\u1ed5ng Gi\u00e1m \u0110\u1ed1c - IMP - T\u1ea1i B\u1eafc Giang - Thu Nh\u1eadp 50 - 100 Tri\u1ec7u',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>B\u1eafc Giang</p>",
            short_cities: 'B\u1eafc Giang',
            salary: '50 - 100 tri\u1ec7u',
            updated_at_str: '11 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/pho-tong-giam-doc-imp-tai-bac-giang-thu-nhap-50-100-trieu/1260648.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '13/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 30,
            remain_deadline_by_hour: 741,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng Ty C\u1ed5 Ph\u1ea7n T\u01b0 V\u1ea5n Thi\u1ebft K\u1ebf X\u00e2y D\u1ef1ng V\u00e0 N\u1ed9i Th\u1ea5t An D\u01b0\u01a1ng',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-tu-van-thiet-ke-xay-dung-va-noi-that-an-duong-a6af8d2f9bd6aaa271a1990e36e4ac31-65efd018d3c0a.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tu-van-thiet-ke-xay-dung-va-noi-that-an-duong/165335.html',
            },
            id: 1260634,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh / Sales/ T\u01b0 V\u1ea5n M\u1ea3ng Ki\u1ebfn Tr\u00fac X\u00e2y D\u1ef1ng V\u00e0 N\u1ed9i Th\u1ea5t \u2013 Thu Nh\u1eadp Trung B\u00ecnh Th\u1ef1c T\u1ebf 15 \u2013 20 Tri\u1ec7u/ Th\u00e1ng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '4 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-sales-tu-van-mang-kien-truc-xay-dung-va-noi-that-thu-nhap-trung-binh-thuc-te-15-20-trieu-thang/1260634.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'true',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'true',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N TH\u01af\u01a0NG M\u1ea0I ZINGROUP',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-thuong-mai-zingroup-70d2cd41ad3709d50e72ac44ad520f7b-65f00b4ee368a.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-thuong-mai-zingroup/164368.html',
            },
            id: 1260063,
            title: 'Tr\u01b0\u1edfng Nh\u00f3m B\u00e1n H\u00e0ng - Sales Leader (Thu Nh\u1eadp 30 Tri\u1ec7u Tr\u1edf L\u00ean)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: 'Tr\u00ean 30 tri\u1ec7u',
            updated_at_str: '13 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/truong-nhom-ban-hang-sales-leader-thu-nhap-30-trieu-tro-len/1260063.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N T\u1eacP \u0110O\u00c0N DU L\u1ecaCH TH\u1ebe K\u1ef6',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-tap-doan-du-lich-the-ky-9d2aed5ff33486ea7600e26ef14a1186-656d3bdf3c688.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tap-doan-du-lich-the-ky/159544.html',
            },
            id: 1259836,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh Du L\u1ecbch Ngh\u1ec9 D\u01b0\u1ee1ng ( Kh\u00f4ng Y\u00eau C\u1ea7u Kinh Nghi\u1ec7m, Thu Nh\u1eadp L\u00ean \u0110\u1ebfn 30 Tri\u1ec7u)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: B\u00ecnh Th\u1ea1nh</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '20 - 30 tri\u1ec7u',
            updated_at_str: '3 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-du-lich-nghi-duong-khong-yeu-cau-kinh-nghiem-thu-nhap-len-den-30-trieu/1259836.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['- L\u00e0m vi\u1ec7c t\u1eeb T2 - T7 (Ngh\u1ec9 Ch\u1ee7 nh\u1eadt, S\u00e1ng T2)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH NHA KHOA AN PH\u01af\u1edaC',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/EJmho9XXC6aaaLIdkACoNx8xWUVCijll_1671589394____4fd182dc60aada16b3ead9d7b77c0387.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-nha-khoa-an-phuoc/129418.html',
            },
            id: 1259796,
            title: 'Nh\u00e2n Vi\u00ean D\u1ecbch V\u1ee5 Kh\u00e1ch H\u00e0ng - Thu Nh\u1eadp T\u1eeb 15 Tri\u1ec7u Tr\u1edf L\u00ean (T\u00e2n An - Long An)',
            company_short_description: '',
            cities: "<p style='text-align: left'>Long An: T\u00e2n An</p>",
            short_cities: 'Long An',
            salary: 'Tr\u00ean 15 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-dich-vu-khach-hang-thu-nhap-tu-15-trieu-tro-len-tan-an-long-an/1259796.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng Ty C\u1ed5 Ph\u1ea7n IGB',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-igb-629f0d1798036.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-igb/105173.html',
            },
            id: 1259733,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh/Sale (Ch\u1ebf \u0110\u1ed9 H\u1ea5p D\u1eabn, Thu Nh\u1eadp T\u1eeb 20 - 50 Tri\u1ec7u)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: C\u1ea7u Gi\u1ea5y</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '20 - 50 tri\u1ec7u',
            updated_at_str: '14 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-sale-che-do-hap-dan-thu-nhap-tu-20-50-trieu/1259733.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH X\u00c2Y D\u1ef0NG V\u00c0 TH\u01af\u01a0NG M\u1ea0I TH\u1ebe GI\u1edaI S\u00c0N',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-tnhh-xay-dung-va-thuong-mai-the-gioi-san-47fa8feaa9c6923e6a40db1a26e7ceb9-64ccd17132d22.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-xay-dung-va-thuong-mai-the-gioi-san/150083.html',
            },
            id: 1259726,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh S\u00e0n G\u1ed7 Thu Nh\u1eadp T\u1eeb 15 - 20 Tri\u1ec7u T\u1ea1i H\u00e0 \u0110\u00f4ng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: H\u00e0 \u0110\u00f4ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 20 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-san-go-thu-nhap-tu-15-20-trieu-tai-ha-dong/1259726.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY CP B\u1ea4T \u0110\u1ed8NG S\u1ea2N HECO LAND',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/ffb98db45eb8a5afc3352f70d5cf360e-65ee5d7add17f.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-cp-bat-dong-san-heco-land/165193.html',
            },
            id: 1259699,
            title: 'C\u1ed9ng T\u00e1c Vi\u00ean Kinh Doanh B\u0110S Nh\u00e0 Ph\u1ed1 (Thu Nh\u1eadp Tr\u00ean 30 Tri\u1ec7u - T\u1ef1 Do Th\u1eddi Gian)',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: 'Tr\u00ean 30 tri\u1ec7u',
            updated_at_str: '8 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/cong-tac-vien-kinh-doanh-bds-nha-pho-thu-nhap-tren-30-trieu-tu-do-thoi-gian/1259699.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '12/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 29,
            remain_deadline_by_hour: 717,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH PH\u00c2N PH\u1ed0I TR\u1ef0C TUY\u1ebeN NH\u1ea4T NH\u1ea4T',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/tanA7fZKQuwiJ90n2XkG9LlxBxDXga8a_1667439578____c436e351067c26274342b45371a8214d.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-phan-phoi-truc-tuyen-nhat-nhat/124888.html',
            },
            id: 1258951,
            title: 'D\u01b0\u1ee3c Ph\u1ea9m Nh\u1ea5t Nh\u1ea5t - Digital Marketing - Facebook Ads (Thu Nh\u1eadp 12 - 25 Tri\u1ec7u) T\u1ea1i H\u00e0 N\u1ed9i',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '15 - 25 tri\u1ec7u',
            updated_at_str: '5 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/duoc-pham-nhat-nhat-digital-marketing-facebook-ads-thu-nhap-12-25-trieu-tai-ha-noi/1258951.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '01/05/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 48,
            remain_deadline_by_hour: 1173,
            is_diamond_employer: 'false',
            is_job_flash: 'true',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:30 \u0111\u1ebfn 17:30)', 'Th\u1ee9 7 (t\u1eeb 08:30 \u0111\u1ebfn 12:00)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH INETKR',
                logo_url: 'https://www.topcv.vn/v4/image/normal-company/logo_default.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-inetkr/161496.html',
            },
            id: 1225808,
            title: 'Senior Front-End ReactJS, Nextjs ( Thu Nh\u1eadp H\u1ea5p D\u1eabn T\u1eeb 20-30 Tri\u1ec7u/Th\u00e1ng)',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 2</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '20 - 30 tri\u1ec7u',
            updated_at_str: '6 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/senior-front-end-reactjs-nextjs-thu-nhap-hap-dan-tu-20-30-trieu-thang/1225808.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'true',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 16:30)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N B\u1ea4T \u0110\u1ed8NG S\u1ea2N BCONS PS',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/2b5ed90a027160c98174b436417a3401-62b9254934f7e.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-bat-dong-san-bcons-ps/108237.html',
            },
            id: 1259635,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh - L\u01b0\u01a1ng C\u1ee9ng \u0110\u1ebfn 15 Tri\u1ec7u/Th\u00e1ng + Hoa H\u1ed3ng 50tr/S\u1ea3n Ph\u1ea9m + H\u1ed7 Tr\u1ee3 100% Data Kh\u00e1ch',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: B\u00ecnh Th\u1ea1nh</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '15 - 50 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-luong-cung-den-15-trieu-thang-hoa-hong-50tr-san-pham-ho-tro-100-data-khach/1259635.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH \u0110\u1ed2 CH\u01a0I TH\u00d4NG MINH SUN VIGOR VI\u1ec6T NAM',
                logo_url: 'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/be8a33699a7b9022f87c5fa4cea94b71-65e94e112a82c.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-do-choi-thong-minh-sun-vigor-viet-nam/164984.html',
            },
            id: 1259602,
            title: 'Ph\u00f3 Ph\u00f2ng Qu\u1ea3n L\u00fd S\u1ea3n Xu\u1ea5t (Thu Nh\u1eadp T\u1eeb 800$) T\u1ea1i H\u1ea3i Ph\u00f2ng',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u1ea3i Ph\u00f2ng: Ti\u00ean L\u00e3ng</p>",
            short_cities: 'H\u1ea3i Ph\u00f2ng',
            salary: 'Tr\u00ean 800 USD',
            updated_at_str: '9 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/pho-phong-quan-ly-san-xuat-thu-nhap-tu-800-tai-hai-phong/1259602.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N T\u1ea6M NH\u00ccN QU\u1ed0C T\u1ebe ALADDIN',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-tam-nhin-quoc-te-aladdin-613f00ea1cee0.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tam-nhin-quoc-te-aladdin/22918.html',
            },
            id: 1259369,
            title: 'L\u1eadp Tr\u00ecnh Vi\u00ean Mobile Flutter (18-22M/ Th\u00e1ng) T\u1ea1i H\u00e0 \u0110\u00f4ng , H\u00e0 N\u1ed9i',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: H\u00e0 \u0110\u00f4ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '18 - 22 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/lap-trinh-vien-mobile-flutter-18-22m-thang-tai-ha-dong-ha-noi/1259369.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N T\u1ea6M NH\u00ccN QU\u1ed0C T\u1ebe ALADDIN',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/cong-ty-co-phan-tam-nhin-quoc-te-aladdin-613f00ea1cee0.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-tam-nhin-quoc-te-aladdin/22918.html',
            },
            id: 1259342,
            title: 'Tr\u01b0\u1edfng Nh\u00f3m Ph\u00e1t Tri\u1ec3n \u1ee8ng D\u1ee5ng PHP (26-30M/ Th\u00e1ng) T\u1ea1i H\u00e0 \u0110\u00f4ng, H\u00e0 N\u1ed9i',
            company_short_description: '',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: H\u00e0 \u0110\u00f4ng</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '26 - 30 tri\u1ec7u',
            updated_at_str: '12 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/truong-nhom-phat-trien-ung-dung-php-26-30m-thang-tai-ha-dong-ha-noi/1259342.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '11/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 28,
            remain_deadline_by_hour: 693,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
        {
            company: {
                name: 'C\u00f4ng ty CP Kinh doanh F88',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/DFtAiouYgEptwb56ISZeWgbcXgmxnLfm_1650885574____64525bcbe563d4a7599cc12cc508db75.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-cp-kinh-doanh-f88/29631.html',
            },
            id: 1259238,
            title: 'Middle/Senior Data Analyst',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Thanh Xu\u00e2n</p>",
            short_cities: 'H\u00e0 N\u1ed9i',
            salary: '22 - 32 tri\u1ec7u',
            updated_at_str: '10 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/middle-senior-data-analyst/1259238.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '10/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 27,
            remain_deadline_by_hour: 669,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:30 \u0111\u1ebfn 17:30)'],
        },
        {
            company: {
                name: 'INTERFRESH FOOD AND BEVERAGE CO LTD',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/tjcw8OxDWByGGUjHlvDNa9vzIMVXds9P_1695075398____f83f1accc8baa68ad0ec3cf817a9ce10.jpg',
                url: 'https://www.topcv.vn/cong-ty/interfresh-food-and-beverage-co-ltd/153891.html',
            },
            id: 1259133,
            title: 'Chuy\u00ean Vi\u00ean Marketing B2B - Thu Nh\u1eadp L\u00ean \u0110\u1ebfn 25 Tri\u1ec7u T\u1ea1i B\u00ecnh D\u01b0\u01a1ng',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>B\u00ecnh D\u01b0\u01a1ng: D\u0129 An<br/>H\u1ed3 Ch\u00ed Minh: Th\u1ee7 \u0110\u1ee9c</p>",
            short_cities: 'B\u00ecnh D\u01b0\u01a1ng, H\u1ed3 Ch\u00ed Minh',
            salary: '18 - 25 tri\u1ec7u',
            updated_at_str: '9 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/chuyen-vien-marketing-b2b-thu-nhap-len-den-25-trieu-tai-binh-duong/1259133.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '10/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 27,
            remain_deadline_by_hour: 669,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:00 \u0111\u1ebfn 17:00)', 'Th\u1ee9 7 (t\u1eeb 08:00 \u0111\u1ebfn 12:00)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY TNHH SUNSHINE SHARE VI\u1ec6T NAM',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/Lzlr1Jq1jZ2QPDOSqXKC0o14CCrZWcI8_1709719343____fb09d4601caaa2f9acece0b1b774e9fc.png',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-tnhh-sunshine-share-viet-nam/164900.html',
            },
            id: 1259049,
            title: 'Nh\u00e2n Vi\u00ean Kinh Doanh Bi\u1ebft Ti\u1ebfng Trung, Thu Nh\u1eadp L\u00ean \u0110\u1ebfn 30 Tri\u1ec7u, L\u00e0m T\u1ea1i Qu\u1eadn 7',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u1ed3 Ch\u00ed Minh: Qu\u1eadn 7</p>",
            short_cities: 'H\u1ed3 Ch\u00ed Minh',
            salary: '15 - 30 tri\u1ec7u',
            updated_at_str: '11 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'true',
            url: 'https://www.topcv.vn/viec-lam/nhan-vien-kinh-doanh-biet-tieng-trung-thu-nhap-len-den-30-trieu-lam-tai-quan-7/1259049.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'true',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '10/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 27,
            remain_deadline_by_hour: 669,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'false',
            apply_url: 'false',
            is_apply: 'false',
            working_times: ['Th\u1ee9 2 - Th\u1ee9 6 (t\u1eeb 08:30 \u0111\u1ebfn 17:30)'],
        },
        {
            company: {
                name: 'C\u00d4NG TY C\u1ed4 PH\u1ea6N VINSCHOOL',
                logo_url:
                    'https://cdn-new.topcv.vn/unsafe/200x/https://static.topcv.vn/company_logos/IWgswbwUnoLOrYkhMlzv0jHNxbWU3kgz_1633685713____cac5f742fc82a09850b270566e892324.jpg',
                url: 'https://www.topcv.vn/cong-ty/cong-ty-co-phan-vinschool/77305.html',
            },
            id: 1258988,
            title: 'Gi\u00e1o Vi\u00ean Ti\u1ebfng Anh (C\u1ea5p Trung H\u1ecdc)',
            company_short_description: 'null',
            cities: "<p style='text-align: left'>H\u00e0 N\u1ed9i: Gia L\u00e2m, Long Bi\u00ean, Hai B\u00e0 Tr\u01b0ng, Nam T\u1eeb Li\u00eam, Ho\u00e0i \u0110\u1ee9c<br/>H\u1ea3i Ph\u00f2ng: H\u1ed3ng B\u00e0ng<br/>Thanh Ho\u00e1: TP Thanh Ho\u00e1<br/>H\u01b0ng Y\u00ean: V\u0103n Giang</p>",
            short_cities: 'H\u00e0 N\u1ed9i & 3 n\u01a1i kh\u00e1c',
            salary: '20 - 35 tri\u1ec7u',
            updated_at_str: '19 gi\u1edd tr\u01b0\u1edbc',
            is_featured: 'false',
            url: 'https://www.topcv.vn/viec-lam/giao-vien-tieng-anh-cap-trung-hoc/1258988.html?ta_source=DashboardJob_LinkDetail',
            is_highlight: 'false',
            is_urgent: 'false',
            is_new: 'false',
            is_paid_featured: 'false',
            is_hot: 'false',
            is_bg_featured: 'true',
            is_remote: 'false',
            deadline: '10/04/2024',
            is_vip_employer: 'false',
            remain_deadline_by_day: 27,
            remain_deadline_by_hour: 669,
            is_diamond_employer: 'false',
            is_job_flash: 'false',
            employer_verified: 'true',
            apply_url: 'false',
            is_apply: 'false',
            working_times: [],
        },
    ];

    const showApply = () => {
        dispatch(showModal());
    };

    return (
        <div className={cx('wrapper')} id="job-search-detail-body">
            <Modal>
                <ModalApplyComponent job={job} />
            </Modal>
            <HeaderDynamic job={job} state={stateTab} />
            <div className={cx('container')}>
                <div className={cx('tab', state !== 'company' ? 'off' : '')}>
                    <CompanySummary company={job.company} />
                </div>
                <div className={cx('title', state !== 'info' ? 'off' : '')}>Chi tiết tuyển dụng</div>
                <div className={cx('info', state !== 'info' ? 'off' : '')}>
                    <JobSummary job={job} />
                </div>
                <div className={cx('content', state !== 'info' ? 'off' : '')}>
                    <div className={cx('description')}>
                        {listDescription.map((item) => (
                            <div className={cx('description-item')} key={item.id}>
                                <h3 className={cx('title-item')}>{item.title}</h3>
                                <div className={cx('content-item')} dangerouslySetInnerHTML={{ __html: item.content }}></div>
                            </div>
                        ))}
                        <div className={cx('description-item')}>
                            <h3 className={cx('title-item')}>Cách thức ứng tuyển</h3>
                            <div className={cx('content-item')}>
                                Ứng viên nộp hồ sơ trực tuyến bằng cách bấm
                                <strong> Ứng tuyển </strong>
                                ngay dưới đây.
                            </div>
                        </div>
                    </div>
                </div>
                <div className={cx('action', state !== 'info' ? 'off' : '')}>
                    <div className={cx('action-item', 'apply')}>
                        <button className={cx('action-button')} onClick={showApply}>
                            Ứng tuyển ngay
                        </button>
                        <button className={cx('action-button')}>Lưu tin</button>
                    </div>
                    <div className={cx('action-item', 'applied', 'hidden')}>
                        <button className={cx('action-button')} onClick={showApply}>
                            Ứng tuyển ngay
                        </button>
                        <button className={cx('action-button')}>Lưu tin</button>
                    </div>
                    <div className={cx('deadline')}>Hạn nộp hồ sơ: {job.deadline}</div>
                    <div className={cx('quantity', 'disabled')}>
                        <div className={cx('quantity-icon')}>
                            <FaLock className={cx('icon-lock')} />
                        </div>
                        <div className={cx('text')}>TVNow chưa hỗ trợ xem số lượt ứng tuyển cho việc làm này</div>
                    </div>
                </div>
                <div className={cx('report', state !== 'info' ? 'off' : '')}>
                    <span className={cx('report-icon')}>
                        <FaCircleInfo className={cx('icon-info')} />
                    </span>
                    <span className={cx('report-text')}>
                        Báo cáo tin tuyển dụng: Nếu bạn thấy rằng tin tuyển dụng này không đúng hoặc có dấu hiệu lừa đảo,{' '}
                        <button className={cx('report-button')}>hãy phản ánh với chúng tôi.</button>
                    </span>
                </div>
                <div className={cx('update-info', state !== 'info' ? 'off' : '')}>
                    <img src={images.cv} alt="cv" className={cx('img-cv')} />
                    <div className={cx('update-content')}>
                        <p className={cx('update-title')}>
                            Số lượng NTD tìm kiếm những ứng viên như bạn đã
                            {stateTrend.status === 'up' ? ' tăng lên' : ' giảm đi'} khoảng <span className={cx('highlight')}> {stateTrend.percent}%</span> trong
                            1 tuần gần đây.
                        </p>
                    </div>
                    <div className={cx('chart')}>
                        <div className={cx('chart-percent')}>
                            {stateTrend.status === 'up' ? <HiArrowTrendingUp className={cx('icon-up')} /> : <HiArrowTrendingDown className={cx('icon-down')} />}
                            <span className={cx('percent')}>{stateTrend.percent}%</span>
                        </div>
                        <img src={images.chart} alt="chart" className={cx('img-chart', { down: stateTrend.status === 'down' })} />
                    </div>
                </div>
                <div className={cx('job-category', state !== 'info' ? 'off' : '')}>
                    <JobCategory job={job} />
                </div>
                <div className={cx('job-suitable', state !== 'info' ? 'off' : '')}>
                    <JobSuitable job={job} />
                </div>
                <div className={cx('job-report', state !== 'info' ? 'off' : '')}>
                    <JobReport />
                </div>
                <div className={cx('job-similar', state !== 'related' ? 'off' : '')} id="job-search-detail-similar">
                    <h2 className={cx('job-similar-title')}>Việc làm liên quan</h2>
                    <div className={cx('job-similar-list')}>
                        {suggest_jobs.slice(0, 20).map((job) => (
                            <JobSuggest job={job} key={job.id} />
                        ))}
                    </div>
                </div>
                <div className={cx('job-course')} id="job-search-detail-course">
                    <SuggestCourseSlide />
                </div>
            </div>
        </div>
    );
};

JobDetailBody.propTypes = {
    job: PropTypes.object.isRequired,
    state: PropTypes.string.isRequired,
};

export default JobDetailBody;
